"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from raccoon import DigitalSensor, Motor, MotorCalibration
from raccoon import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.675694940295412e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6467330773068776e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6841676201509747e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6788360868058874e-05, vel_lpf_alpha=1.0
        ),
    )
    analog_sensors = []


defs = Defs()

__all__ = ["Defs", "defs"]
