"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from raccoon import DigitalSensor, IRSensor, Motor, MotorCalibration, Servo, ServoPreset
from raccoon import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_ir_sensor = IRSensor(port=0)
    front_right_ir_sensor = IRSensor(port=1)
    rear_left_ir_sensor = IRSensor(port=2)
    rear_right_ir_sensor = IRSensor(port=3)
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.7409814711185985e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.7781536518103197e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.733677900926751e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.7553647250614497e-05, vel_lpf_alpha=1.0
        ),
    )
    arm_servo = ServoPreset(Servo(port=0), positions={"up": 75, "down": 165})
    claw_servo = ServoPreset(Servo(port=1), positions={"open": 75, "closed": 175})
    analog_sensors = [
        front_left_ir_sensor,
        front_right_ir_sensor,
        rear_left_ir_sensor,
        rear_right_ir_sensor,
    ]


defs = Defs()

__all__ = ["Defs", "defs"]
